import jwtDecode from "jwt-decode";

export interface JwtHeader {
  type: string
  alg: string
  kid: string
}

export interface JwtPayload {
  iss: string
  aud: string
  nonce?: string
  identityscheme: string
  authenticationtype: string
  authenticationinstant: string

  nameidentifier: string
  sub: string

  [key: string]: any

  iat: number
  nbf: number
  exp: number
}

export type Sample = {
  jwt: string
  header: JwtHeader
  payload: JwtPayload
}

function toSample(jwt: string) : Sample {
  return {
    jwt,
    header: jwtDecode<JwtHeader>(jwt, {header: true}),
    payload: jwtDecode<JwtPayload>(jwt, {header: false})
  };
}

export const MITID_CITIZEN = toSample('eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjExMjc3MEEzNjZERkJERjRCRURBM0QyMkM2NDFERDg4QTI2N0E4NjcifQ.eyJpc3MiOiJodHRwczovL3NhbXBsZXMuY3JpaXB0by5pZCIsImF1ZCI6InVybjpjcmlpcHRvOnNhbXBsZXM6Y3JpaXB0by1qd3Qtdmlld2VyIiwibm9uY2UiOiJlY25vbi1kZjU5ZDZlMS01MjYwLTRmZmItOWNkMi04Yzg2ZmM5OWQ1NzYiLCJpZGVudGl0eXNjaGVtZSI6ImRrbWl0aWQiLCJhdXRoZW50aWNhdGlvbnR5cGUiOiJ1cm46Z3JuOmF1dGhuOmRrOm1pdGlkOmxvdyIsImF1dGhlbnRpY2F0aW9ubWV0aG9kIjoicHdkOjE2Njk4MDExODM3NTE6TE9XOlNVQlNUQU5USUFMOkxPVzpMT1ciLCJhdXRoZW50aWNhdGlvbmluc3RhbnQiOiIyMDIyLTExLTMwVDA5OjM5OjQ2LjE1MFoiLCJuYW1laWRlbnRpZmllciI6IjNhOGYxNzk4YTUyMjQwNTc5YmZhNjllMTA2ZDNkMmVlIiwic3ViIjoiezNhOGYxNzk4LWE1MjItNDA1Ny05YmZhLTY5ZTEwNmQzZDJlZX0iLCJzZXNzaW9uaW5kZXgiOiIwNmY0NGRiMC1kNWQ1LTRhNTgtOTI5NS00ZTZiOGI0ZGJlYmIiLCJsb0EiOiJMT1ciLCJpYWwiOiJTVUJTVEFOVElBTCIsImFhbCI6IkxPVyIsImZhbCI6IkhJR0giLCJ1dWlkIjoiOGU2YWI0ZWEtNThiOS00MTMwLWE5MDAtNDM2NmJhNTRlZWQ5IiwiY3ByTnVtYmVySWRlbnRpZmllciI6IjI3MTI1ODkxMDAiLCJiaXJ0aGRhdGUiOiIxOTU4LTEyLTI3IiwiZGF0ZW9mYmlydGgiOiIxOTU4LTEyLTI3IiwiYWdlIjoiNjMiLCJuYW1lIjoiUGFpbWFuIFBldGVyc2VuIiwicmVmVGV4dEhlYWRlciI6IkxvZyBvbiBhdCBDcmlpcHRvIiwicmVmVGV4dEJvZHkiOiJAY3JpaXB0by9qd3Qtdmlld2VyIiwiY291bnRyeSI6IkRLIiwiaWF0IjoxNjY5ODAxMTg2LCJuYmYiOjE2Njk4MDExODYsImV4cCI6MTY2OTgxOTE4M30.YVdVd6WUQ4pALWjTGsTaIRqn4cqTKnXM7mXzGRdL-RXkW7ejGs-KlKFP-35HgTMw7uz7EinHGrfAlVR56A4yrCJRLvKiqvP5VyLo-Ohf4AuFfo4Zw9ZanGRuplYChGoM0vw9pgZUtxvkbTrh3Nhi12jBaldfwgNTNss3UIbU4jnIe5OsyDNEBZYKjBJMxk6e5aeb4YSAuIlG-SMTrvaAH47P5V-bNZckmqO16Mlt9edYz2fo6ELBfz1M4G65HdNW5dHFGWbFCoR3LxRICX1JAoxbF4-');