import jwtDecode from "jwt-decode";

export interface JwtHeader {
  type: string
  alg: string
  kid: string
}

export type JwtPayloadObjectValue = {[key: string]: JwtPayloadValue}
export type JwtPayloadValue = string | number | JwtPayloadObjectValue
export interface JwtPayload {
  iss: string
  aud: string
  nonce?: string
  identityscheme: string
  authenticationtype: string
  authenticationinstant: string

  nameidentifier: string
  sub: string

  [key: string]: JwtPayloadValue | undefined

  iat: number
  nbf: number
  exp: number
}

export type Sample = {
  jwt: string
  header: JwtHeader
  payload: JwtPayload
}

function toSample(jwt: string) : Sample {
  return {
    jwt,
    header: jwtDecode<JwtHeader>(jwt, {header: true}),
    payload: jwtDecode<JwtPayload>(jwt, {header: false})
  };
}

export const MITID_CITIZEN = toSample('eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjExMjc3MEEzNjZERkJERjRCRURBM0QyMkM2NDFERDg4QTI2N0E4NjcifQ.eyJpc3MiOiJodHRwczovL3NhbXBsZXMuY3JpaXB0by5pZCIsImF1ZCI6InVybjpjcmlpcHRvOnNhbXBsZXM6Y3JpaXB0by1qd3Qtdmlld2VyIiwibm9uY2UiOiJlY25vbi1kZjU5ZDZlMS01MjYwLTRmZmItOWNkMi04Yzg2ZmM5OWQ1NzYiLCJpZGVudGl0eXNjaGVtZSI6ImRrbWl0aWQiLCJhdXRoZW50aWNhdGlvbnR5cGUiOiJ1cm46Z3JuOmF1dGhuOmRrOm1pdGlkOmxvdyIsImF1dGhlbnRpY2F0aW9ubWV0aG9kIjoicHdkOjE2Njk4MDExODM3NTE6TE9XOlNVQlNUQU5USUFMOkxPVzpMT1ciLCJhdXRoZW50aWNhdGlvbmluc3RhbnQiOiIyMDIyLTExLTMwVDA5OjM5OjQ2LjE1MFoiLCJuYW1laWRlbnRpZmllciI6IjNhOGYxNzk4YTUyMjQwNTc5YmZhNjllMTA2ZDNkMmVlIiwic3ViIjoiezNhOGYxNzk4LWE1MjItNDA1Ny05YmZhLTY5ZTEwNmQzZDJlZX0iLCJzZXNzaW9uaW5kZXgiOiIwNmY0NGRiMC1kNWQ1LTRhNTgtOTI5NS00ZTZiOGI0ZGJlYmIiLCJsb0EiOiJMT1ciLCJpYWwiOiJTVUJTVEFOVElBTCIsImFhbCI6IkxPVyIsImZhbCI6IkhJR0giLCJ1dWlkIjoiOGU2YWI0ZWEtNThiOS00MTMwLWE5MDAtNDM2NmJhNTRlZWQ5IiwiY3ByTnVtYmVySWRlbnRpZmllciI6IjI3MTI1ODkxMDAiLCJiaXJ0aGRhdGUiOiIxOTU4LTEyLTI3IiwiZGF0ZW9mYmlydGgiOiIxOTU4LTEyLTI3IiwiYWdlIjoiNjMiLCJuYW1lIjoiUGFpbWFuIFBldGVyc2VuIiwicmVmVGV4dEhlYWRlciI6IkxvZyBvbiBhdCBDcmlpcHRvIiwicmVmVGV4dEJvZHkiOiJAY3JpaXB0by9qd3Qtdmlld2VyIiwiY291bnRyeSI6IkRLIiwiaWF0IjoxNjY5ODAxMTg2LCJuYmYiOjE2Njk4MDExODYsImV4cCI6MTY2OTgxOTE4M30.YVdVd6WUQ4pALWjTGsTaIRqn4cqTKnXM7mXzGRdL-RXkW7ejGs-KlKFP-35HgTMw7uz7EinHGrfAlVR56A4yrCJRLvKiqvP5VyLo-Ohf4AuFfo4Zw9ZanGRuplYChGoM0vw9pgZUtxvkbTrh3Nhi12jBaldfwgNTNss3UIbU4jnIe5OsyDNEBZYKjBJMxk6e5aeb4YSAuIlG-SMTrvaAH47P5V-bNZckmqO16Mlt9edYz2fo6ELBfz1M4G65HdNW5dHFGWbFCoR3LxRICX1JAoxbF4-');
export const MITID_CITIZEN_ADDRESS = toSample('eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjExMjc3MEEzNjZERkJERjRCRURBM0QyMkM2NDFERDg4QTI2N0E4NjcifQ.eyJpc3MiOiJodHRwczovL3NhbXBsZXMuY3JpaXB0by5pZCIsImF1ZCI6InVybjpjcmlpcHRvOnNhbXBsZXM6Y3JpaXB0by1qd3Qtdmlld2VyIiwibm9uY2UiOiJlY25vbi05NGY1NjkzZi05YWRmLTQ1NjEtOGUzYy01YjIwOTg2NGVlMjYiLCJpZGVudGl0eXNjaGVtZSI6ImRrbWl0aWQiLCJhdXRoZW50aWNhdGlvbnR5cGUiOiJ1cm46Z3JuOmF1dGhuOmRrOm1pdGlkOmxvdyIsImF1dGhlbnRpY2F0aW9ubWV0aG9kIjoicHdkOjE2Njk4MTE0NzA2NzM6TE9XOlNVQlNUQU5USUFMOkxPVzpMT1ciLCJhdXRoZW50aWNhdGlvbmluc3RhbnQiOiIyMDIyLTExLTMwVDEyOjMxOjEzLjUxMloiLCJuYW1laWRlbnRpZmllciI6IjNhOGYxNzk4YTUyMjQwNTc5YmZhNjllMTA2ZDNkMmVlIiwic3ViIjoiezNhOGYxNzk4LWE1MjItNDA1Ny05YmZhLTY5ZTEwNmQzZDJlZX0iLCJzZXNzaW9uaW5kZXgiOiIwNmY0NGRiMC1kNWQ1LTRhNTgtOTI5NS00ZTZiOGI0ZGJlYmIiLCJhZGRyZXNzIjp7ImZvcm1hdHRlZCI6IlR1c25pbGRhIEthbW1hIE9sc2VuXG5HcnVzZ3JhdmVuIDEsMyB0dlxuMzQwMCBIaWxsZXLDuGRcbihMb2thbGl0ZXQgdWtlbmR0KVxuRGFubWFyayIsImNvbW1vbl9uYW1lIjoiVHVzbmlsZGEgS2FtbWEgT2xzZW4iLCJzdHJlZXRfYWRkcmVzcyI6IkdydXNncmF2ZW4gMSwzIHR2IiwicG9zdGFsX2NvZGUiOiIzNDAwIiwiY2l0eSI6IkhpbGxlcsO4ZCIsImxvY2FsaXR5IjoiKExva2FsaXRldCB1a2VuZHQpIiwicmVnaW9uIjpudWxsLCJjb3VudHJ5IjoiRGFubWFyayJ9LCJhZGRyZXNzX2RldGFpbHMiOnsicm9hZCI6IkdydXNncmF2ZW4iLCJyb2FkX2NvZGUiOiIxNzMyIiwibXVuaWNpcGFsaXR5IjoiTHluZ2J5LVRhYXJiw6ZrIiwibXVuaWNpcGFsaXR5X2NvZGUiOiIwMTczIiwiaG91c2VfbnVtYmVyIjoiMDAxIiwiZmxvb3IiOiIwMyIsImFwYXJ0bWVudF9jb2RlIjoiICB0diJ9LCJsb0EiOiJMT1ciLCJpYWwiOiJTVUJTVEFOVElBTCIsImFhbCI6IkxPVyIsImZhbCI6IkhJR0giLCJ1dWlkIjoiOGU2YWI0ZWEtNThiOS00MTMwLWE5MDAtNDM2NmJhNTRlZWQ5IiwiY3ByTnVtYmVySWRlbnRpZmllciI6IjI3MTI1ODkxMDAiLCJiaXJ0aGRhdGUiOiIxOTU4LTEyLTI3IiwiZGF0ZW9mYmlydGgiOiIxOTU4LTEyLTI3IiwiYWdlIjoiNjMiLCJuYW1lIjoiUGFpbWFuIFBldGVyc2VuIiwicmVmVGV4dEhlYWRlciI6IkxvZyBvbiBhdCBDcmlpcHRvIiwicmVmVGV4dEJvZHkiOiJAY3JpaXB0by9qd3Qtdmlld2VyIiwiY291bnRyeSI6IkRLIiwiaWF0IjoxNjY5ODExNDczLCJuYmYiOjE2Njk4MTE0NzMsImV4cCI6MTY2OTgyOTQ3MH0.ViEKKVynUYSfVXOd5Tm_uW0zell-30lUwuRjbk2NK9LBDxLm61MYLfyezdZi4yR8C4GomlfDxaLmGnBBN6FcLb3ZJS9n3VG1apI9u3fsLAwz3_VWgYE_Qx0omEI0DI7Yp49M6cnQBezCvZLaB4PRySZV_24X5T1ZSMkdM5t6sgl3tfndTOXrRBRZlbbuTOVaBQv4MsgdeoctPGzVav8bUx970AGszoZDtfEJIjhmtkHqlbPOB8IymzEciRASjnweSmzWzLWE9e-iGWd9IuHZ3TfMVrK43yvBwPf6LNOd2ge933ztZdfUgsMIOIrAURaNtvNk0sL-0PKFrl9Cs0fbuQ');